# Generated by Django 3.0.3 on 2020-04-14 15:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('live_forcast_app', '0002_auto_20200407_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveforcast',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
