# Generated by Django 3.0.3 on 2020-04-16 21:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_forcast_app', '0003_auto_20200414_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveforcast',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
