# Generated by Django 3.0.3 on 2020-04-14 17:15

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_urgentmessage_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=150)),
                ('bible_ref', models.TextField()),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('detail', models.TextField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='sermonUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=500, verbose_name='Link to Video Source (e.g Youtube.)')),
                ('image', models.ImageField(upload_to='images', verbose_name='Image of a Scene During The Service')),
                ('sermonTitle', models.CharField(max_length=100, verbose_name='Sermon Title')),
                ('precherName', models.CharField(max_length=70, verbose_name='Officiating Minister')),
            ],
        ),
        migrations.CreateModel(
            name='subcribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RenameField(
            model_name='setcountdowndate',
            old_name='Active',
            new_name='active',
        ),
        migrations.AddField(
            model_name='displaysilder',
            name='title',
            field=models.CharField(default=True, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urgentmessage',
            name='userImage',
            field=models.ImageField(default=True, upload_to='images', verbose_name='User Passport(with any background'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='displaysilder',
            name='discriptionBottom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='displaysilder',
            name='discriptionTop',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='setcountdowndate',
            name='eventDate',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='urgentmessage',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='urgentmessage',
            name='messageBody',
            field=ckeditor.fields.RichTextField(verbose_name='Message Body'),
        ),
    ]
