# Generated by Django 3.0.3 on 2020-04-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200414_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='sm_phone_display',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('discriptionTop', models.CharField(blank=True, max_length=40, null=True)),
                ('discriptionBottom', models.CharField(blank=True, max_length=100, null=True)),
                ('displayImage', models.ImageField(upload_to='images')),
            ],
        ),
    ]
