# Generated by Django 3.0.3 on 2020-04-16 21:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20200416_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermonupdate',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image of a Scene During The Service'),
        ),
        migrations.AlterField(
            model_name='sm_phone_display',
            name='displayImage',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='urgentmessage',
            name='userImage',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='User Passport(with any background'),
        ),
    ]
