# Generated by Django 3.0.3 on 2020-04-16 21:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20200416_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urgentmessage',
            name='userImage',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
