# Generated by Django 3.0.3 on 2020-04-16 21:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='featuredImage',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='blog',
            name='userPicture',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
