# Generated by Django 3.0.3 on 2020-04-16 21:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0005_auto_20200406_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstminister',
            name='picture',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='secondminister',
            name='picture',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='testimony_s',
            name='featuredImage',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='testimony_s',
            name='userPicture',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='thirdminister',
            name='picture',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
